kubernetes:
  enabled: true

agent:
  unprivileged: true
  presets:
    perNode:
      serviceAccount:
        create: false
        name: user-sa
    clusterWide:
      serviceAccount:
        create: false
        name: user-sa
    ksmSharded:
      serviceAccount:
        create: false
        name: user-sa
